//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServisApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeknikServisEntities : DbContext
    {
        public TeknikServisEntities()
            : base("name=TeknikServisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<ArizaDetay> ArizaDetay { get; set; }
        public virtual DbSet<Cariler> Cariler { get; set; }
        public virtual DbSet<Departman> Departman { get; set; }
        public virtual DbSet<FaturaBaslik> FaturaBaslik { get; set; }
        public virtual DbSet<FaturaDetay> FaturaDetay { get; set; }
        public virtual DbSet<Gider> Gider { get; set; }
        public virtual DbSet<Kategori> Kategori { get; set; }
        public virtual DbSet<Notlar> Notlar { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Urun> Urun { get; set; }
        public virtual DbSet<UrunHareket> UrunHareket { get; set; }
        public virtual DbSet<UrunKabul> UrunKabul { get; set; }
        public virtual DbSet<UrunTakip> UrunTakip { get; set; }
    }
}
